### ISSUE TITLE
Add image for Brighton MathsJam

### ISSUE THREAD

**Issue by katiesteckles** [dabapps/brightonbrains#18]
Hello! I'm the organiser of MathsJam internationally, and Adam who runs the Brighton one has requested I send you our logo to add to your site. Here's one: https://mathsjam.com/assets/logos/mathsjam.png
Hope that helps! Good work and thanks.

**Comment by katiesteckles** [comment]
(also, MathsJam is on the second-to-last Tuesday, not Thursday!)

**Comment by JakeSidSmith** [comment]
Ooops, sorry about that. Typo on my part. Will get these sorted asap. 🙂
